version: '3'
services:
  # build the application dockerfile stored in the same folder
  app:
    build: .

  # db dockerfile is in the db folder
  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always