version: '3'
services:
  # build the application dockerfile stored in the same folder
  app:
    build: .
    ports:
      - "8080:8080"

  # db dockerfile is in the db folder
  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
  web:
    build: web/.
    restart: always
    ports:
      - "80:80"